AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  DictionaryFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        dictionary:
          Type: Api
          Properties:
            Path: /hello
            Method: get
    Metadata:
      DockerTag: nodejs20.x-v1
      DockerContext: ./dictionary
      Dockerfile: Dockerfile

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  dictionaryApi:
    Description: "API Gateway endpoint URL for Prod stage for dictionary function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  dictionaryFunction:
    Description: "dictionary Lambda Function ARN"
    Value: !GetAtt DictionaryFunction.Arn
  dictionaryFunctionIamRole:
    Description: "Implicit IAM Role created for dictionary function"
    Value: !GetAtt DictionaryFunctionRole.Arn
